---
- hosts: localhost
  gather_facts: true
  become: true

  pre_tasks:
      - name: Update cache
        apt:
            update_cache: true
            cache_valid_time: 3600

  tasks:
      - name: Install ZSH
        include_tasks:
            file: tasks/zsh.yml
            apply:
                tags:
                    - zsh
        tags:
            - zsh

      - name: Install Node
        include_tasks:
            file: tasks/node.yml
            apply:
                tags:
                    - node
        tags:
            - node

      - name: Add Scripts
        include_tasks:
            file: tasks/scripts.yml
            apply:
                tags:
                    - scripts
        tags:
            - scripts

      - name: Install Go
        include_tasks:
            file: tasks/go.yml
            apply:
                tags:
                    - go
        tags:
            - go
