- name: Install nodejs
  apt:
    pkg:
      - nodejs
      - npm
  tags:
    - node

- name: Install n
  npm:
    name: n
    global: true
  tags:
    - node

- name: Install Node 20.12.0
  shell: n 20.12.0
  tags:
    - node
