- name: Install ZSH
  apt:
      name: zsh

- name: Change shell
  shell: chsh -s `which zsh`

- name: Install OhMyZsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

- name: Install the zsh autosuggestion plugin
  git:
      repo: https://github.com/zsh-users/zsh-autosuggestions
      dest: ~/.oh-my-zsh/plugins/zsh-autosuggestions

- name: update our zshrc
  shell: sed -i '/plugins=(git)/c\plugins=(git zsh-autosuggestions)' ~/.zshrc

- name: update our .zshrc file to use autosuggestion, z, git and sudo plugins
  ansible.builtin.lineinfile:
      path: ~/.zshrc
      regexp: "^plugins="
      line: "plugins=(git z zsh-autosuggestions sudo)"
